name: ahpsico
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  mvvm_riverpod: ^1.1.0
  flutter_dotenv: ^5.1.0
  firebase_crashlytics: ^3.3.3
  intl: ^0.18.1
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1
  meta: ^1.9.1
  collection: ^1.17.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  go_router: ^9.0.3
  logger: ^1.4.0
  mask_text_input_formatter: ^2.4.0
  stack_trace: ^1.11.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.12
  flutter_neat_and_clean_calendar: ^0.3.13+28
  upgrader: ^8.0.0
  firebase_remote_config: ^4.2.4
  shared_preferences: ^2.2.0

dependency_overrides:
  macos_ui:
    git:
      url: https://github.com/Mayb3Nots/macos_ui.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  sqflite_common_ffi: ^2.2.5
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
          style: normal
